server:
  port: 9092
#Spring
spring:
  profiles:
    active: dev
  devtools:
    livereload:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    validation-query: SELECT 1
    url: jdbc:mysql://localhost:3306/openhire-users
    username: openhire
    password: openhire



##spring.jpa.properties.javax.persistence.schema-generation.scripts.create-target=build/duhire.sql
##spring.jpa.properties.javax.persistence.schema-generation.scripts.action=create
#URLS
##duhire.email.server=http://localhost:9091/api/email
##duhire.confirm_client_user.server=http://localhost:9090/api/petition/client/confirm/
